### ISSUE TITLE
1.1.0 release checklist

### ISSUE THREAD

**Issue by Jashepp** [Unchosen/require-worker#4]
The following is a checklist of work required before 1.1.0 release.

- [x] Write Tests.
- [x] Setup Travis CI.
- [ ] Write Benchmarks - *In Progress*.
- [ ] Write API Docs - *In Progress*.
- [ ] Improve README - *In Progress*.
- [ ] Write Examples - *In Progress*.
- [ ] Write Wiki (maybe it can explain things in great detail?)

Features:

- [x] Be better than concept release.
- [ ] Implement recursive proxies (result proxies & etc). This includes the `forceProxy` proxy call option.
- [ ] Implement the `objectPath` proxy call option.
- [ ] Implement proxy call options or something to deal with eventEmitters, streams and etc.
- [ ] Implement some sort of proxy idle check or proxy destruction after use.
- [ ] Add support for nodejs --inspect
- [x] Use nodejs cluster fork by default
